# Generated by Django 3.0.5 on 2020-04-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Игрок рейтинга',
                'verbose_name_plural': 'Игроки рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Изображение')),
                ('conference', models.CharField(choices=[('E', 'Eastern'), ('W', 'Western')], max_length=255)),
                ('seasons_played', models.PositiveIntegerField()),
                ('cup_appearances', models.PositiveIntegerField()),
                ('titles', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.RatingPlayer', verbose_name='Игрок')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Изображение')),
                ('country', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[('R', 'Right Wing'), ('L', 'Left Wing'), ('C', 'Center'), ('D', 'Defense')], max_length=255)),
                ('games_played', models.PositiveIntegerField()),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Team')),
            ],
        ),
    ]
