# Generated by Django 3.0.5 on 2020-04-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_auto_20200424_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Конференция', 'verbose_name_plural': 'Конференции'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='ratingplayer',
            options={'verbose_name': 'Звездный игрок', 'verbose_name_plural': 'Звездные игроки'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
